### ISSUE TITLE
gamma-cli deploy: doesn't always work

### ISSUE THREAD

**Issue by eyalorbs** [orbs-network/orbs-contract-sdk#36] opened 2018-12-05 14:32 UTC
sometimes when deploying a smart contract the following error appears:

![screen shot 2018-12-05 at 15 13 59](https://user-images.githubusercontent.com/45359306/49520138-44131f00-f8ab-11e8-9a6a-0dc74b58b410.png)

when attempting to deploy again it usually works. I have encountered this error multiple times

**Comment by talkol** [comment] 2018-12-05 23:05
This error happens if you send the transaction too quickly before the server is listening

@EsterEdelstein that's why we added the `-wait` flag for `start-local`
the problem is that `gamma-cli start-local -wait` takes too long
what do you want to do?

**Comment by talkol** [comment] 2018-12-12 06:46
I think for starters we should improve the error message to say:

"Server did not start yet, please try again in a few seconds"

**Comment by EsterEdelstein** [comment] 2018-12-12 08:13
Agree with the suggestion to add the message. 
If we will see that he happens too often we will consider a different solution.

**Comment by EsterEdelstein** [comment] 2018-12-24 09:06
closing

**Closed by EsterEdelstein** 2018-12-24 09:06 UTC
